package service

import (
	"errors"
	"net/http"
	"path"
	"strconv"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"cloudchat/internal/database"
	"cloudchat/internal/models"
	"github.com/redis/go-redis/v9"
)

const (
	// MaxFileSize is the largest file a client may upload.
	MaxFileSize = 10 << 20
	// MaxRoomFileBytes bounds the total upload volume per room.
	MaxRoomFileBytes = 50 << 20

	maxFileNameLength = 200
)

var (
	ErrFileNotFound = errors.New("file not found")
	ErrRoomQuota    = errors.New("room file storage limit reached")
	ErrFileEmpty    = errors.New("file is empty")
	ErrFileTooLarge = errors.New("file is too large")
)

var inlineImageTypes = map[string]bool{"image/png": true, "image/jpeg": true, "image/gif": true, "image/webp": true}

// reserveQuotaLua atomically adds to a room's upload total, refusing (and
// rolling back) if it would exceed the limit.
var reserveQuotaLua = redis.NewScript(`
local used = redis.call('INCRBY', KEYS[1], ARGV[1])
if used > tonumber(ARGV[2]) then
  redis.call('DECRBY', KEYS[1], ARGV[1])
  return 0
end
redis.call('EXPIRE', KEYS[1], ARGV[3])
return 1
`)

// FileKeyPrefix is the prefix of a room's file keys; the file ID follows it.
func FileKeyPrefix(roomID string) string { return "room:" + roomID + ":file:" }

func fileKey(roomID, fileID string) string { return FileKeyPrefix(roomID) + fileID }

// RoomFileBytesKey tracks a room's total upload volume for the quota.
func RoomFileBytesKey(roomID string) string { return "room:" + roomID + ":filebytes" }

// RoomFilesKey is a set of the room's file IDs, so all of its files can be
// found (e.g. to expire them when the room empties).
func RoomFilesKey(roomID string) string { return "room:" + roomID + ":files" }

// InlineImage reports whether a stored MIME type is a raster image that is
// safe to display inline. Everything else is served as a download.
func InlineImage(mime string) bool { return inlineImageTypes[mime] }

// ValidFileID reports whether id has the format generated by SaveFile.
func ValidFileID(id string) bool { return validRandomID(id) }

// SanitizeFileName strips any path and control characters from a client
// supplied name and bounds its length.
func SanitizeFileName(name string) string {
	name = path.Base(strings.ReplaceAll(name, "\\", "/"))
	name = strings.Map(func(r rune) rune {
		if unicode.IsControl(r) || r == utf8.RuneError {
			return -1
		}
		return r
	}, name)
	name = strings.TrimSpace(name)
	if utf8.RuneCountInString(name) > maxFileNameLength {
		name = string([]rune(name)[:maxFileNameLength])
	}
	if name == "" || name == "." || name == "/" {
		name = "file"
	}
	return name
}

// SaveFile stores a file for the room, expiring after ttl, and returns its
// metadata (without URL). The MIME type is sniffed from the content rather
// than trusted from the client.
func SaveFile(roomID, name string, data []byte, ttl time.Duration) (*models.FileInfo, error) {
	size := int64(len(data))
	if size == 0 {
		return nil, ErrFileEmpty
	}
	if size > MaxFileSize {
		return nil, ErrFileTooLarge
	}

	quotaKey := RoomFileBytesKey(roomID)
	ok, err := reserveQuotaLua.Run(database.Ctx, database.RDB, []string{quotaKey},
		size, MaxRoomFileBytes, int(ttl.Seconds())).Int()
	if err != nil {
		return nil, err
	}
	if ok == 0 {
		return nil, ErrRoomQuota
	}

	id, err := newRandomID()
	if err != nil {
		database.RDB.DecrBy(database.Ctx, quotaKey, size)
		return nil, err
	}
	info := &models.FileInfo{
		ID:   id,
		Name: SanitizeFileName(name),
		Size: size,
		Mime: http.DetectContentType(data),
	}

	key := fileKey(roomID, id)
	_, err = database.RDB.TxPipelined(database.Ctx, func(p redis.Pipeliner) error {
		p.HMSet(database.Ctx, key, "name", info.Name, "mime", info.Mime, "size", size, "data", data)
		p.Expire(database.Ctx, key, ttl)
		p.SAdd(database.Ctx, RoomFilesKey(roomID), id)
		p.Expire(database.Ctx, RoomFilesKey(roomID), ttl)
		return nil
	})
	if err != nil {
		database.RDB.DecrBy(database.Ctx, quotaKey, size)
		return nil, err
	}
	return info, nil
}

type StoredFile struct {
	models.FileInfo
	Data []byte
}

func GetFile(roomID, fileID string) (*StoredFile, error) {
	vals, err := database.RDB.HMGet(database.Ctx, fileKey(roomID, fileID), "name", "mime", "size", "data").Result()
	if err != nil {
		return nil, err
	}
	data, ok := vals[3].(string)
	if !ok {
		return nil, ErrFileNotFound
	}
	name, _ := vals[0].(string)
	mime, _ := vals[1].(string)
	sizeStr, _ := vals[2].(string)
	size, _ := strconv.ParseInt(sizeStr, 10, 64)
	return &StoredFile{
		FileInfo: models.FileInfo{ID: fileID, Name: name, Mime: mime, Size: size},
		Data:     []byte(data),
	}, nil
}
