package service

import (
	"errors"
	"fmt"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"strconv"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"cloudchat/internal/database"
	"cloudchat/internal/models"
	"github.com/redis/go-redis/v9"
)

const (
	// MaxFileSize is the largest file a client may upload.
	MaxFileSize = 10 << 20
	// MaxRoomFileBytes bounds the total upload volume per room.
	MaxRoomFileBytes = 50 << 20

	maxFileNameLength = 200
)

var (
	ErrFileNotFound = errors.New("file not found")
	ErrRoomQuota    = errors.New("room file storage limit reached")
	ErrFileEmpty    = errors.New("file is empty")
	ErrFileTooLarge = errors.New("file is too large")
)

var inlineImageTypes = map[string]bool{"image/png": true, "image/jpeg": true, "image/gif": true, "image/webp": true}

// reserveQuotaLua atomically adds to a room's upload total, refusing (and
// rolling back) if it would exceed the limit.
var reserveQuotaLua = redis.NewScript(`
local used = redis.call('INCRBY', KEYS[1], ARGV[1])
if used > tonumber(ARGV[2]) then
  redis.call('DECRBY', KEYS[1], ARGV[1])
  return 0
end
redis.call('EXPIRE', KEYS[1], ARGV[3])
return 1
`)

// FileKeyPrefix is the prefix of a room's file keys; the file ID follows it.
func FileKeyPrefix(roomID string) string { return "room:" + roomID + ":file:" }

func fileKey(roomID, fileID string) string { return FileKeyPrefix(roomID) + fileID }

// RoomFileBytesKey tracks a room's total upload volume for the quota.
func RoomFileBytesKey(roomID string) string { return "room:" + roomID + ":filebytes" }

// RoomFilesKey is a set of the room's file IDs, so all of its files can be
// found (e.g. to expire them when the room empties).
func RoomFilesKey(roomID string) string { return "room:" + roomID + ":files" }

// InlineImage reports whether a stored MIME type is a raster image that is
// safe to display inline. Everything else is served as a download.
func InlineImage(mime string) bool { return inlineImageTypes[mime] }

// ValidFileID reports whether id has the format generated by SaveFile.
func ValidFileID(id string) bool { return validRandomID(id) }

// SanitizeFileName strips any path and control characters from a client
// supplied name and bounds its length.
func SanitizeFileName(name string) string {
	name = path.Base(strings.ReplaceAll(name, "\\", "/"))
	name = strings.Map(func(r rune) rune {
		if unicode.IsControl(r) || r == utf8.RuneError {
			return -1
		}
		return r
	}, name)
	name = strings.TrimSpace(name)
	if utf8.RuneCountInString(name) > maxFileNameLength {
		name = string([]rune(name)[:maxFileNameLength])
	}
	if name == "" || name == "." || name == "/" {
		name = "file"
	}
	return name
}

// SaveFile stores a file for the room, expiring after ttl, and returns its
// metadata (without URL). The content goes to disk (see InitFileStore);
// Redis keeps only the name, type and size, and expiring that makes the
// file unavailable at once. The MIME type is sniffed from the content
// rather than trusted from the client.
func SaveFile(roomID, name string, src io.Reader, size int64, ttl time.Duration) (*models.FileInfo, error) {
	if size == 0 {
		return nil, ErrFileEmpty
	}
	if size > MaxFileSize {
		return nil, ErrFileTooLarge
	}

	quotaKey := RoomFileBytesKey(roomID)
	ok, err := reserveQuotaLua.Run(database.Ctx, database.RDB, []string{quotaKey},
		size, MaxRoomFileBytes, int(ttl.Seconds())).Int()
	if err != nil {
		return nil, err
	}
	if ok == 0 {
		return nil, ErrRoomQuota
	}
	saved := false
	defer func() {
		if !saved {
			database.RDB.DecrBy(database.Ctx, quotaKey, size)
		}
	}()

	id, err := newRandomID()
	if err != nil {
		return nil, err
	}
	path := filePath(roomID, id)
	mime, written, err := writeFile(path, src)
	if err != nil {
		return nil, err
	}
	if written != size {
		os.Remove(path)
		if written > MaxFileSize {
			return nil, ErrFileTooLarge
		}
		return nil, fmt.Errorf("file is %d bytes, expected %d", written, size)
	}
	info := &models.FileInfo{ID: id, Name: SanitizeFileName(name), Size: size, Mime: mime}

	key := fileKey(roomID, id)
	_, err = database.RDB.TxPipelined(database.Ctx, func(p redis.Pipeliner) error {
		p.HMSet(database.Ctx, key, "name", info.Name, "mime", info.Mime, "size", size)
		p.Expire(database.Ctx, key, ttl)
		p.SAdd(database.Ctx, RoomFilesKey(roomID), id)
		p.Expire(database.Ctx, RoomFilesKey(roomID), ttl)
		return nil
	})
	if err != nil {
		os.Remove(path)
		return nil, err
	}
	saved = true
	filesUsed.Add(size)
	return info, nil
}

// writeFile writes src to path through a temporary file, so a half-written
// file is never visible, and sniffs the content type from its first bytes.
func writeFile(path string, src io.Reader) (mime string, written int64, err error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return "", 0, err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), tmpPrefix+"*")
	if err != nil {
		return "", 0, err
	}
	defer func() {
		if err != nil {
			tmp.Close()
			os.Remove(tmp.Name())
		}
	}()
	head := make([]byte, 512)
	n, err := io.ReadFull(src, head)
	if err != nil && !errors.Is(err, io.ErrUnexpectedEOF) && !errors.Is(err, io.EOF) {
		return "", 0, err
	}
	head = head[:n]
	if _, err = tmp.Write(head); err != nil {
		return "", 0, err
	}
	rest, err := io.Copy(tmp, io.LimitReader(src, MaxFileSize+1-int64(n)))
	if err != nil {
		return "", 0, err
	}
	if err = tmp.Close(); err != nil {
		return "", 0, err
	}
	if err = os.Rename(tmp.Name(), path); err != nil {
		return "", 0, err
	}
	return http.DetectContentType(head), int64(n) + rest, nil
}

// OpenFile returns a file's metadata and its content, opened for reading.
// The caller must close it. Files whose metadata has expired are not found,
// even if the janitor hasn't removed them from disk yet.
func OpenFile(roomID, fileID string) (*models.FileInfo, *os.File, error) {
	vals, err := database.RDB.HMGet(database.Ctx, fileKey(roomID, fileID), "name", "mime", "size").Result()
	if err != nil {
		return nil, nil, err
	}
	name, ok := vals[0].(string)
	if !ok {
		return nil, nil, ErrFileNotFound
	}
	mime, _ := vals[1].(string)
	sizeStr, _ := vals[2].(string)
	size, _ := strconv.ParseInt(sizeStr, 10, 64)
	f, err := os.Open(filePath(roomID, fileID))
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil, ErrFileNotFound
	}
	if err != nil {
		return nil, nil, err
	}
	return &models.FileInfo{ID: fileID, Name: name, Mime: mime, Size: size}, f, nil
}
