package service

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"strconv"
	"time"

	"cloudchat/internal/database"
	"cloudchat/internal/models"
	"github.com/redis/go-redis/v9"
)

const (
	// MaxSecretAttempts is how many wrong passwords destroy a secret.
	MaxSecretAttempts = 5
	// MaxCiphertextBytes bounds the decoded ciphertext size.
	MaxCiphertextBytes = 48 * 1024

	minIterations = 100_000
	maxIterations = 10_000_000
	ivBytes       = 12
	saltBytes     = 16
	authBytes     = 32
)

var SecretTTLs = map[string]time.Duration{
	"1d":  24 * time.Hour,
	"7d":  7 * 24 * time.Hour,
	"30d": 30 * 24 * time.Hour,
}

var (
	ErrSecretNotFound  = errors.New("secret not found")
	ErrSecretDestroyed = errors.New("secret destroyed after too many wrong attempts")
	ErrWrongPassword   = errors.New("wrong password")
)

// ValidationError reports a malformed request.
type ValidationError struct{ Msg string }

func (e *ValidationError) Error() string { return e.Msg }

func invalid(format string, args ...any) error {
	return &ValidationError{Msg: fmt.Sprintf(format, args...)}
}

func secretKey(id string) string { return "secret:" + id }

// ValidSecretID reports whether id has the format generated by CreateSecret.
func ValidSecretID(id string) bool { return validRandomID(id) }

func decodeExact(field, s string, n int) ([]byte, error) {
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil || len(b) != n {
		return nil, invalid("%s must be %d bytes of base64", field, n)
	}
	return b, nil
}

func verifierFor(auth string) (string, error) {
	b, err := decodeExact("auth", auth, authBytes)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:]), nil
}

func CreateSecret(req *models.CreateSecretRequest) (*models.CreateSecretResponse, error) {
	ttl, ok := SecretTTLs[req.TTL]
	if !ok {
		return nil, invalid("ttl must be one of 1d, 7d, 30d")
	}
	if req.Iterations < minIterations || req.Iterations > maxIterations {
		return nil, invalid("iterations must be between %d and %d", minIterations, maxIterations)
	}
	ct, err := base64.StdEncoding.DecodeString(req.Ciphertext)
	if err != nil || len(ct) == 0 {
		return nil, invalid("ciphertext must be non-empty base64")
	}
	if len(ct) > MaxCiphertextBytes {
		return nil, invalid("secret is too large")
	}
	if _, err := decodeExact("iv", req.IV, ivBytes); err != nil {
		return nil, err
	}
	if _, err := decodeExact("salt", req.Salt, saltBytes); err != nil {
		return nil, err
	}
	verifier, err := verifierFor(req.Auth)
	if err != nil {
		return nil, err
	}

	id, err := newRandomID()
	if err != nil {
		return nil, err
	}

	key := secretKey(id)
	_, err = database.RDB.TxPipelined(database.Ctx, func(p redis.Pipeliner) error {
		// HMSet rather than multi-field HSet keeps Redis < 4.0 supported.
		p.HMSet(database.Ctx, key,
			"ciphertext", req.Ciphertext,
			"iv", req.IV,
			"salt", req.Salt,
			"iterations", req.Iterations,
			"verifier", verifier,
			"attempts", 0,
		)
		p.Expire(database.Ctx, key, ttl)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &models.CreateSecretResponse{ID: id, ExpiresAt: time.Now().Add(ttl)}, nil
}

// DeleteSecret removes a secret note; it reports whether it existed.
func DeleteSecret(id string) (bool, error) {
	n, err := database.RDB.Del(database.Ctx, secretKey(id)).Result()
	return n > 0, err
}

// GetSecretMeta returns key-derivation parameters without consuming the secret.
func GetSecretMeta(id string) (*models.SecretMeta, error) {
	key := secretKey(id)
	var fields *redis.SliceCmd
	var ttl *redis.DurationCmd
	_, err := database.RDB.Pipelined(database.Ctx, func(p redis.Pipeliner) error {
		fields = p.HMGet(database.Ctx, key, "salt", "iterations", "attempts")
		ttl = p.PTTL(database.Ctx, key)
		return nil
	})
	if err != nil {
		return nil, err
	}
	vals := fields.Val()
	salt, _ := vals[0].(string)
	if salt == "" || ttl.Val() <= 0 {
		return nil, ErrSecretNotFound
	}
	iterStr, _ := vals[1].(string)
	attStr, _ := vals[2].(string)
	iterations, _ := strconv.Atoi(iterStr)
	attempts, _ := strconv.Atoi(attStr)
	return &models.SecretMeta{
		Salt:         salt,
		Iterations:   iterations,
		ExpiresAt:    time.Now().Add(ttl.Val()),
		AttemptsLeft: MaxSecretAttempts - attempts,
	}, nil
}

// revealScript atomically checks the verifier and, on success, returns the
// ciphertext and deletes the secret; on failure it counts the attempt and
// deletes the secret once attempts run out.
var revealScript = redis.NewScript(`
if redis.call('EXISTS', KEYS[1]) == 0 then return {0} end
if redis.call('HGET', KEYS[1], 'verifier') == ARGV[1] then
  local d = redis.call('HMGET', KEYS[1], 'ciphertext', 'iv')
  redis.call('DEL', KEYS[1])
  return {1, d[1], d[2]}
end
local left = tonumber(ARGV[2]) - redis.call('HINCRBY', KEYS[1], 'attempts', 1)
if left <= 0 then redis.call('DEL', KEYS[1]) end
return {2, left}
`)

// RevealSecret releases the ciphertext exactly once. On a wrong password it
// returns ErrWrongPassword with the number of attempts left.
func RevealSecret(id, auth string) (*models.RevealedSecret, int, error) {
	verifier, err := verifierFor(auth)
	if err != nil {
		return nil, 0, err
	}
	res, err := revealScript.Run(database.Ctx, database.RDB,
		[]string{secretKey(id)}, verifier, MaxSecretAttempts).Slice()
	if err != nil {
		return nil, 0, err
	}
	switch res[0].(int64) {
	case 1:
		ct, _ := res[1].(string)
		iv, _ := res[2].(string)
		return &models.RevealedSecret{Ciphertext: ct, IV: iv}, 0, nil
	case 2:
		left := int(res[1].(int64))
		if left <= 0 {
			return nil, 0, ErrSecretDestroyed
		}
		return nil, left, ErrWrongPassword
	default:
		return nil, 0, ErrSecretNotFound
	}
}
